language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zarak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zarak/react-test npm test

after_success:
  - docker build -t zarak/multi-client ./client
  - docker build -t zarak/multi-nginx ./nginx
  - docker build -t zarak/multi-server ./server
  - docker build -t zarak/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zarak/multi-client
  - docker push zarak/multi-nginx
  - docker push zarak/multi-server
  - docker push zarak/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-012195179707
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
